---
box_version: 0.1.6
memory: 1024
cpus: 1
provider: virtualbox
bridge_interface: ''

#authorize: ~/.ssh/id_rsa.pub

#keys:
#    - ~/.ssh/id_rsa

networking:
    - public: true

folders:
    - map: ''
      to: /home/vagrant/app
      type: nfs

ports:
    - guest: 80
      host: 8000
    - guest: 27017
      host: 27017
    - guest: 3000
      host: 3000

sites:
    - map: webiny.dev
      to: /home/vagrant/app/public_html
      host: 8000