---
name: "wbiny-dev-2"
ip: "192.168.22.22"
memory: 1024
cpus: 1
provider: virtualbox
#bridge_interface: "en0: Wi-Fi 2 (AirPort)"

#authorize: ~/.ssh/id_rsa.pub

#keys:
#    - ~/.ssh/id_rsa

networking:
    - public: true

folders:
    - map: Code
      to: /home/vagrant/code
      type: nfs

ports:
    - guest: 80
      host: 8000
    - guest: 27017
      host: 27017
    - guest: 3000
      host: 3000