---
ip: "192.168.22.22"
memory: 1024
cpus: 2
provider: virtualbox

#authorize: ~/.ssh/id_rsa.pub

#keys:
#    - ~/.ssh/id_rsa

networking:
    - public: true

folders:
    - map: ~/Code
      to: /home/vagrant/Code
      type: nfs

#sites:
#  - map: webiny.dev
#    to: /home/vagrant/Code/Webiny/public